# Generated by Django 2.0 on 2019-04-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, max_length=100, null=True)),
                ('econtent', models.TextField(blank=True, null=True)),
                ('ecreater', models.CharField(blank=True, max_length=40, null=True)),
                ('eloc', models.CharField(blank=True, max_length=40, null=True)),
                ('estartdt', models.DateField(blank=True, null=True)),
                ('estarttm', models.TimeField(blank=True, null=True)),
                ('eenddt', models.DateField(blank=True, null=True)),
                ('eendtm', models.TimeField(blank=True, null=True)),
                ('eprice', models.IntegerField(blank=True, null=True)),
                ('emaxattendee', models.IntegerField(blank=True, null=True)),
                ('eculattendee', models.IntegerField(blank=True, null=True)),
                ('eimage', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
    ]
